steps:
  - name: python
    args:
      - install
      - '-r'
      - requirements.txt
      - '--user'
    entrypoint: pip
  - name: python
    args:
      - testcomposer.py
      - '--dags_directory=dags'
      - '--dags_bucket=us-central1-example-environ-04ac8194-bucket'
    entrypoint: python
  
options:
  logging: CLOUD_LOGGING_ONLY
