steps:
  - name: python
    args:
      - install
      - '-r'
      - requirements.txt
      - '--user'
    entrypoint: pip
  - name: python
    args:
      - testcomposer.py
      - '--dags_directory=${_DAGS_DIRECTORY}'
      - '--dags_bucket=${_DAGS_BUCKET}'
    entrypoint: python
  - name: bash
    args:
      - echo
      - Hello world!
    entrypoint: bash
options:
  logging: NONE
