steps:
  # install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # run
  - name: python
    entrypoint: python
    args: ["/testcomposer.py", "--dags_directory=${_DAGS_DIRECTORY}", "--dags_bucket=${_DAGS_BUCKET}"]

  
options:
  logging: CLOUD_LOGGING_ONLY
