steps:
  # install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "/requirements.txt", "--user"]

  # run
  - name: python
    entrypoint: python
    args: ["/*.py", "--dags_directory=${_DAGS_DIRECTORY}", "--dags_bucket=${_DAGS_BUCKET}"]
    dir: "gs://testingpurpose/logs/python"

  - name: bash
    entrypoint: bash
    args: ["echo", "Hello world!"]
    dir: "gs://testingpurpose/logs/bash"
